[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "crypto>=1.4.1",
    "pycryptodome>=3.23.0",
    "websockets>=15.0.1",
]
